package EpidemicInfo

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	NoticeApi
	Test_swabApi
	Clock_inApi
	QuarantineApi
	VaccineApi
	MigrationApi
	AreaApi
	QuestionnaireApi
	Fill_inApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
