package EpidemicInfo

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	ThermographApi
	Temp_measureApi
	QuarantineApi
	Quarantine_siteApi
	AreaApi
	Clock_inApi
	MigrationApi
	QuestionnaireApi
	Fill_inApi
	VaccineApi
	Test_swabApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
