package EpidemicInfo

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	Quarantine_siteApi
	AreaApi
	MigrationApi
	QuestionnaireApi
	Fill_inApi
	VaccineApi
	NoticeApi
	Test_swabApi
	Clock_inApi
	QuarantineApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
