package EpidemicInfo


type ServiceGroup struct {
    // Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	NoticeService
	Test_swabService
	Clock_inService
	QuarantineService
	VaccineService
	MigrationService
	AreaService
	QuestionnaireService
	Fill_inService
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}

