package EpidemicInfo


type ServiceGroup struct {
    // Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	StudentService
	CounselorService
	ThermographService
	Temp_measureService
	QuarantineService
	Quarantine_siteService
	AreaService
	Clock_inService
	VaccineService
	ManufacturerService
	Test_swabService
	LabService
	MigrationService
	QuestionnaireService
	Fill_inService
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}

