package EpidemicInfo

type RouterGroup struct {
    // Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	StudentRouter
	CounselorRouter
	ThermographRouter
	Temp_measureRouter
	QuarantineRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
